# ruff_config.toml - standalone
output-format = "concise"
preview = true
lint.select = [
"F632",
"E721",
"E722",
"TRY004",
"TRY201",
"TRY002",
"TRY203",
"TRY300",
"TRY301",
"BLE001",
"B004",
"B006",
"B008",
"B012",
"B017",
"B013",
"B014",
"B016",
"B029",
"B030",
"RSE102",
"PLE0116",
"PLE0643",
"PLE0704"
]
target-version = "py310"
