# ruff_config.toml - standalone
output-format = "concise"
preview = true
lint.select = [
	"F406", "PLW0642", "F823"	
	"B014", "B025",
	"PIE794", "PYI062",
	"PLE0241",
	"PLR0913", "PLR0911", "PLR0915",
	"ARG001", "ARG002", "ARG003", "ARG004", "ARG005",

]
target-version = "py310"

[format]
quote-style = "double"
