# ruff_config.toml - standalone
output-format = "concise"
preview = true
lint.select = [	#naming convention
		"N801", "N802", "N803", "N804", "N805", "N806", "N807", 
    		"N811", "N812", "N813", "N814", "N815", "N816", "N817", 
    		"N818", "N999",
		#unnecessary whitespaces
		"E201", "E202", "E203", "E211", "E225", "E226", "E227",
		"E228", "E231", "E252", "E275", "W291", "W293", "E306", 
		"E301",	"E114", "E115", "E116",
		"E301",
		"FURB187",
		"RUF018",
		"PLR6104",
		"RET504",
		"PLR2004",
		"SIM101",
		"B033",
		"PLR2044",
		"SIM202",
		"SIM102"
]
line-length = 100
target-version = "py310"

[format]
quote-style = "double"
